const DEFAULT_ROLES = [
  {
    name: 'Editor',
    description: 'Editor can create and update metrics and dashboards.',
    companyId: 'will be replaced dynamically',
    permissions: {
      sql: ['View', 'Edit', 'SQL Mode'],
      joins: ['View', 'Create', 'Edit', 'Delete'],
      roles: [],
      sorts: ['View', 'Create', 'Edit', 'Delete'],
      users: [],
      metric: ['Create', 'Edit', 'Delete', 'Archive', 'Clone', 'Auto Save'],
      actions: ['View', 'Edit'],
      'all-sql': true,
      filters: [
        'View',
        'Create All',
        'Create Simple Filters',
        'Create Complex Filters',
        'Create Client Filters',
        'Edit',
        'Delete',
      ],
      forcast: ['View', 'Edit', 'Enable/Disable'],
      groupby: ['View', 'Edit'],
      'all-joins': true,
      'all-sorts': true,
      apiTokens: [],
      dashboard: [
        'Create',
        'Edit',
        'Manage Metrics',
        'Share',
        'Change Layout',
        'Set Default Client',
      ],
      drilldown: ['View', 'Edit', 'Cross Filter Dashboard', 'Enable/Disable'],
      uiTheming: [],
      workspace: [],
      'all-metric': true,
      appearance: ['View', 'Edit'],
      demoConfig: [],
      fullscreen: [
        'View',
        'Preview Results',
        'Download Table Results',
        'Download Raw CSV',
        'Email CSV',
        'Save PNG',
      ],
      groupXAxis: ['View', 'Edit', 'Enable/Disable'],
      switchAxis: ['View', 'Edit', 'Enable/Disable'],
      'all-actions': true,
      'all-filters': true,
      'all-forcast': true,
      'all-groupby': true,
      datasources: [],
      groupbyAxis: ['View', 'Edit', 'Dynamic Options', 'Enable/Disable'],
      metricsStore: ['View', 'Publish', 'Delete'],
      'all-drilldown': true,
      cacheSettings: [],
      metricFilters: [
        'View',
        'Create',
        'Edit',
        'Delete',
        'App Filters',
        'Manual Options',
        'Variable Filter',
      ],
      python: ['View', 'Edit'],
      'all-appearance': true,
      'all-fullscreen': true,
      'all-groupXAxis': true,
      'all-switchAxis': true,
      'all-python': true,
      archiveMetrics: ['View', 'Unarchive', 'Delete', 'View Client Metrics'],
      companyProfile: [],
      customDatasets: ['View', 'Create', 'Edit', 'Delete'],
      rowsAndColumns: [
        'View Aggregate',
        'Select Aggregate',
        'View Custom SQL',
        'Edit Custom SQL',
      ],
      versionHistory: ['View', 'Switch'],
      'all-groupbyAxis': true,
      cardClickAction: ['View', 'Edit', 'Enable/Disable'],
      'all-metricsStore': true,
      chartClickAction: ['View', 'Edit', 'Enable/Disable'],
      dashboardFilters: ['Create', 'Edit', 'Delete'],
      downloadSettings: [],
      accessPermissions: [],
      'all-metricFilters': true,
      scheduledSettings: [],
      'all-archiveMetrics': true,
      'all-customDatasets': true,
      'all-rowsAndColumns': true,
      'all-versionHistory': true,
      whitelistedDomains: [],
      'all-cardClickAction': true,
      'all-chartClickAction': true,
      'all-dashboardFilters': true,
      dataSecuritySettings: ['View', 'Edit'],
      'all-dataSecuritySettings': true,
      secrets: ['View', 'Create', 'Edit', 'Delete'],
      'all-secrets': true,
    },
  },
  {
    name: 'Viewer',
    description: 'Viewer can view dashboards.',
    companyId: 'will be replaced dynamically',
    permissions: {
      sql: [],
      joins: [],
      roles: [],
      sorts: [],
      users: [],
      metric: [],
      actions: [],
      filters: [],
      forcast: [],
      groupby: [],
      apiTokens: [],
      dashboard: ['Share'],
      drilldown: [],
      uiTheming: [],
      workspace: [],
      appearance: [],
      demoConfig: [],
      fullscreen: [
        'View',
        'Preview Results',
        'Download Table Results',
        'Download Raw CSV',
        'Email CSV',
        'Save PNG',
      ],
      groupXAxis: [],
      switchAxis: [],
      datasources: [],
      groupbyAxis: [],
      metricsStore: [],
      'all-dashboard': false,
      cacheSettings: [],
      metricFilters: [],
      'all-fullscreen': true,
      archiveMetrics: [],
      companyProfile: [],
      customDatasets: [],
      rowsAndColumns: [],
      versionHistory: [],
      python: [],
      cardClickAction: [],
      chartClickAction: [],
      dashboardFilters: [],
      downloadSettings: [],
      accessPermissions: [],
      scheduledSettings: [],
      whitelistedDomains: [],
      dataSecuritySettings: [],
    },
  },
  {
    name: 'Developer',
    description:
      'Developer can access metrics and developer specific settings.',
    companyId: 'will be replaced dynamically',
    permissions: {
      sql: ['View', 'Edit', 'SQL Mode'],
      joins: ['View', 'Create', 'Edit', 'Delete'],
      roles: [],
      sorts: ['View', 'Create', 'Edit', 'Delete'],
      users: [],
      metric: ['Create', 'Edit', 'Clone', 'Auto Save'],
      actions: ['View', 'Edit'],
      'all-sql': true,
      filters: [
        'View',
        'Create All',
        'Create Simple Filters',
        'Create Complex Filters',
        'Create Client Filters',
        'Edit',
        'Delete',
      ],
      forcast: ['View', 'Edit', 'Enable/Disable'],
      groupby: ['View', 'Edit'],
      'all-joins': true,
      'all-sorts': true,
      apiTokens: ['View', 'Create', 'Edit', 'Copy', 'Delete'],
      dashboard: ['Share'],
      drilldown: ['View', 'Edit', 'Cross Filter Dashboard', 'Enable/Disable'],
      uiTheming: ['View', 'Create', 'Edit', 'Delete', 'Mark Default'],
      workspace: ['Settings'],
      appearance: ['View', 'Edit'],
      demoConfig: ['View', 'Edit', 'Delete'],
      fullscreen: [
        'View',
        'Preview Results',
        'Download Table Results',
        'Download Raw CSV',
        'Email CSV',
        'Save PNG',
      ],
      groupXAxis: ['View', 'Edit', 'Enable/Disable'],
      switchAxis: ['View', 'Edit', 'Enable/Disable'],
      'all-actions': true,
      'all-filters': true,
      'all-forcast': true,
      'all-groupby': true,
      datasources: [
        'View',
        'Connect',
        'Sync',
        'Delete',
        'Edit Credentials',
        'Edit Tenancy Level',
        'Enable/Disable',
      ],
      groupbyAxis: ['View', 'Edit', 'Dynamic Options', 'Enable/Disable'],
      metricsStore: ['View'],
      'all-apiTokens': true,
      'all-drilldown': true,
      'all-uiTheming': true,
      cacheSettings: ['View', 'Edit', 'Connect'],
      metricFilters: [
        'View',
        'Create',
        'Edit',
        'Delete',
        'App Filters',
        'Manual Options',
        'Variable Filter',
      ],
      'all-appearance': true,
      'all-demoConfig': true,
      'all-fullscreen': true,
      'all-groupXAxis': true,
      'all-switchAxis': true,
      archiveMetrics: ['View', 'View Client Metrics'],
      companyProfile: [],
      customDatasets: ['View', 'Create', 'Edit', 'Delete'],
      rowsAndColumns: [
        'View Aggregate',
        'Select Aggregate',
        'View Custom SQL',
        'Edit Custom SQL',
      ],
      versionHistory: ['View', 'Switch'],
      python: ['View', 'Edit'],
      'all-datasources': true,
      'all-groupbyAxis': true,
      'all-python': true,
      cardClickAction: ['View', 'Edit', 'Enable/Disable'],
      chartClickAction: ['View', 'Edit', 'Enable/Disable'],
      dashboardFilters: [],
      downloadSettings: ['View', 'Edit'],
      accessPermissions: [
        'View',
        'Edit',
        'Metric Creation',
        'Metric Updation',
        'Customize Layout',
        'Archive Metrics',
        'Schedule Reports',
      ],
      'all-cacheSettings': true,
      'all-metricFilters': true,
      scheduledSettings: ['View', 'Edit', 'Clear'],
      'all-customDatasets': true,
      'all-rowsAndColumns': true,
      'all-versionHistory': true,
      whitelistedDomains: ['View', 'Edit', 'Remove'],
      'all-cardClickAction': true,
      'all-chartClickAction': true,
      'all-downloadSettings': true,
      dataSecuritySettings: ['View', 'Edit'],
      'all-accessPermissions': true,
      'all-scheduledSettings': true,
      'all-whitelistedDomains': true,
      'all-dataSecuritySettings': true,
      secrets: ['View', 'Create', 'Edit', 'Delete'],
      'all-secrets': true,
    },
  },
];

export default DEFAULT_ROLES;
