export const metricList = [
  {
    isArchived: false,
    isCreatedByClient: false,
    isEnableGroupBy: false,
    isLive: false,
    isMarkedDeleted: false,
    limit: 100,
    clickActions: {
      card: {
        isEnable: false,
        baseUrl: '',
        dynamic: 'none',
        route: '',
        routeType: 'internal',
      },
      chart: {
        isEnable: false,
        baseUrl: '',
        dynamic: '{{value}}',
        route: '/{{value}}',
        routeType: 'internal',
      },
    },
    joinFields: [],
    chartOptions: {
      step: '',
      xAxis: '',
      margins: {
        marginTop: 20,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 20,
      },
      measure: '',
      chartType: 'single value',
      yAxisList: [],
      singleValue: 'total_revenue',
      axisSettings: {
        axis: 'left',
      },
      sankeyValues: [],
      labelSettings: {
        axis: 'left',
        show: false,
        position: 'hidden',
        truncateLabelValue: 14,
      },
      tableSettings: {
        lineGap: 'small',
        enableFilter: true,
        showRowHover: false,
        enableSorting: true,
        showTableDesc: false,
        defaultRowSize: '10',
        showTableTitle: false,
        contentAlignment: 'center',
        enableStripedRows: false,
        enableTableSearch: true,
        hideVerticalDivider: false,
      },
      customSettings: {
        barWidth: 40,
        fontSize: 14,
        barRadius: 0,
        xRotation: 50,
        axisLabels: 'none',
        displayText: '',
        dateFormatter: 'none',
        hideAxisLines: 'none',
        subHeaderShow: false,
        hideSplitLines: 'none',
        numberFormatter: '$',
        showLabelValues: false,
        subHeaderFontSize: 0,
      },
      legendSettings: {
        top: 0,
        left: 0,
        show: true,
        right: 0,
        bottom: 0,
        position: 'horizontal',
        truncateLegendValue: 14,
      },
      backGroundColor: {
        show: false,
      },
      timeSeriesSettings: {
        seriesType: [],
        groupBySettings: {
          value: 'monthly',
          options: [],
          isDynamic: false,
        },
      },
    },
    datasetMetricSettings: {
      sort: '',
      columns: [],
      filters: [],
      metrics: [
        {
          as: '"total_revenue"',
          value: 'SUM("sales")',
        },
      ],
      timeColumn: {
        label: '',
        value: '',
      },
      selectTable: {
        label: 'public.cleaned_sales_data',
        value: 'public.cleaned_sales_data',
      },
      clientColumn: {
        label: '',
        value: '',
      },
      isIncludeTime: false,
      timeGrainValue: '',
      customColumnList: [],
      isSortDescending: false,
      selectedDimensions: [],
    },
    drillDownSettings: null,
    groupBy: false,
    inputFields: [
      {
        column: 'sales',
        datatype: 'double precision',
        tableName: 'cleaned_sales_data',
        schemaName: 'public',
      },
    ],
    resizeAttributes: {
      width: 5,
      xAxis: 0,
      yAxis: 0,
      height: 10,
    },
    rlsConditions: [],
    selectedGroupBy: [],
    clientId: null,
    createdBy: 'Sapna Singh',
    description: '',
    integrationName: 'Redshift',
    metricId: 'demo_total_revenue',
    metricQuery: '',
    name: 'Total Revenue',
    outputColumns: '',
    query:
      'SELECT       SUM("sales") AS "total_revenue"  FROM public.cleaned_sales_data  \n    LIMIT 100',
    timeGrain: null,
    companyId: '5c00f9ce-9153-42cf-a25a-17b422ec38b2',
    companyIntegrationId: 'afa9ad7a-8dbc-4837-9acb-9f0ef6140a63',
  },
  {
    isArchived: false,
    isCreatedByClient: false,
    isEnableGroupBy: false,
    isLive: false,
    isMarkedDeleted: false,
    limit: 100,
    clickActions: {
      card: {
        isEnable: false,
        baseUrl: '',
        dynamic: 'none',
        route: '',
        routeType: 'internal',
      },
      chart: {
        isEnable: false,
        baseUrl: '',
        dynamic: '{{value}}',
        route: '/{{value}}',
        routeType: 'internal',
      },
    },
    joinFields: [],
    chartOptions: {
      step: '',
      xAxis: '__timestamp',
      margins: {
        marginTop: 14,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 5,
      },
      measure: '',
      chartType: 'bar',
      yAxisList: ['sum(sales)'],
      singleValue: '',
      axisSettings: {
        axis: 'left',
      },
      sankeyValues: [],
      labelSettings: {
        axis: 'left',
        show: false,
        position: 'hidden',
        truncateLabelValue: 14,
        truncateLabel: true,
      },
      tableSettings: {
        lineGap: 'small',
        enableFilter: true,
        showRowHover: false,
        enableSorting: true,
        showTableDesc: false,
        defaultRowSize: '10',
        showTableTitle: false,
        contentAlignment: 'center',
        enableStripedRows: false,
        enableTableSearch: true,
        hideVerticalDivider: false,
      },
      customSettings: {
        barWidth: 40,
        fontSize: 14,
        barRadius: 0,
        xRotation: 50,
        axisLabels: 'none',
        displayText: '',
        dateFormatter: 'none',
        hideAxisLines: 'none',
        subHeaderShow: false,
        hideSplitLines: 'none',
        numberFormatter: 'original',
        showLabelValues: false,
        subHeaderFontSize: 0,
      },
      legendSettings: {
        top: 0,
        left: 0,
        show: true,
        right: 0,
        bottom: 0,
        position: 'horizontal',
        truncateLegendValue: 14,
      },
      backGroundColor: {
        show: false,
      },
      timeSeriesSettings: {
        seriesType: [
          {
            type: 'bar',
            column: 'sum(sales)',
          },
        ],
        groupBySettings: {
          value: 'monthly',
          options: [],
          isDynamic: false,
        },
      },
    },
    datasetMetricSettings: {
      sort: '',
      columns: [],
      filters: [],
      metrics: [
        {
          as: '"sales"',
          value: 'SUM("order_date")',
        },
      ],
      timeColumn: {
        label: 'order_date',
        value: 'order_date',
      },
      selectTable: {
        label: 'public.cleaned_sales_data',
        value: 'public.cleaned_sales_data',
      },
      clientColumn: {
        label: '',
        value: '',
      },
      isIncludeTime: false,
      timeGrainValue: '',
      customColumnList: [
        {
          as: '"timestamp"',
          value: "DATE_TRUNC('quarter', order_date)",
        },
      ],
      isSortDescending: false,
      selectedDimensions: [
        'DATE_TRUNC(\'quarter\', order_date)____"timestamp"',
      ],
    },
    drillDownSettings: null,
    groupBy: {},
    inputFields: [
      {
        column: 'order_date',
        datatype: 'timestamp without time zone',
        tableName: 'cleaned_sales_data',
        schemaName: 'public',
      },
      {
        column: 'sales',
        datatype: 'double precision',
        tableName: 'cleaned_sales_data',
        schemaName: 'public',
      },
    ],
    resizeAttributes: {
      width: 5,
      xAxis: 0,
      yAxis: 0,
      height: 10,
    },
    rlsConditions: [],
    selectedGroupBy: [],
    clientId: null,
    createdBy: 'Sapna Singh',
    description: '',
    integrationName: 'Redshift',
    metricId: 'demo_quaterly_revenue',
    metricQuery: '',
    name: 'Quarterly Revenue',
    outputColumns: '',
    query:
      'SELECT DATE_TRUNC(\'quarter\', order_date) AS __timestamp,\r\n       sum(sales) AS "SUM(Sales)"\r\nFROM public.cleaned_sales_data\r\nGROUP BY DATE_TRUNC(\'quarter\', order_date)\r\nORDER BY "SUM(Sales)" DESC limit 100',
    timeGrain: null,
    companyId: '5c00f9ce-9153-42cf-a25a-17b422ec38b2',
    companyIntegrationId: 'afa9ad7a-8dbc-4837-9acb-9f0ef6140a63',
  },
  {
    isArchived: false,
    isCreatedByClient: false,
    isEnableGroupBy: false,
    isLive: false,
    isMarkedDeleted: false,
    limit: 100,
    clickActions: {
      card: {
        isEnable: false,
        baseUrl: '',
        dynamic: 'none',
        route: '',
        routeType: 'internal',
      },
      chart: {
        isEnable: false,
        baseUrl: '',
        dynamic: '{{value}}',
        route: '/{{value}}',
        routeType: 'internal',
      },
    },
    joinFields: [],
    chartOptions: {
      step: '',
      xAxis: 'product_line',
      margins: {
        marginTop: 20,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 20,
      },
      measure: '',
      chartType: 'table',
      yAxisList: ['product_line', '# of products sold'],
      singleValue: '',
      axisSettings: {
        axis: 'left',
      },
      sankeyValues: [],
      labelSettings: {
        axis: 'left',
        show: false,
        position: 'hidden',
        truncateLabelValue: 14,
      },
      tableSettings: {
        lineGap: 'small',
        enableFilter: true,
        showRowHover: false,
        enableSorting: true,
        showTableDesc: false,
        defaultRowSize: '10',
        showTableTitle: false,
        contentAlignment: 'center',
        enableStripedRows: false,
        enableTableSearch: true,
        hideVerticalDivider: false,
      },
      customSettings: {
        barWidth: 40,
        fontSize: 14,
        barRadius: 0,
        xRotation: 50,
        axisLabels: 'none',
        displayText: '',
        dateFormatter: 'none',
        hideAxisLines: 'none',
        subHeaderShow: false,
        hideSplitLines: 'none',
        numberFormatter: 'original',
        showLabelValues: false,
        subHeaderFontSize: 0,
      },
      legendSettings: {
        top: 0,
        left: 0,
        show: true,
        right: 0,
        bottom: 0,
        position: 'horizontal',
        truncateLegendValue: 14,
      },
      backGroundColor: {
        show: false,
      },
      timeSeriesSettings: {
        seriesType: [
          {
            type: 'bar',
            column: '# of products sold',
          },
        ],
        groupBySettings: {
          value: 'monthly',
          options: [],
          isDynamic: false,
        },
      },
    },
    datasetMetricSettings: '',
    drillDownSettings: null,
    groupBy: false,
    inputFields: '',
    resizeAttributes: {
      width: 5,
      xAxis: 0,
      yAxis: 0,
      height: 10,
    },
    rlsConditions: [],
    selectedGroupBy: [],
    clientId: null,
    createdBy: 'Sapna Singh',
    description: '',
    integrationName: 'Redshift',
    metricId: 'demo_total_products_sold',
    metricQuery: '',
    name: 'Total Products Sold (By Product Line)',
    outputColumns: '',
    query:
      'SELECT product_line AS product_line,\r\n       sum(quantity_ordered) AS "# of Products Sold"\r\nFROM public.cleaned_sales_data\r\nGROUP BY product_line\r\nORDER BY "# of Products Sold" DESC limit 100',
    timeGrain: null,
    companyId: '5c00f9ce-9153-42cf-a25a-17b422ec38b2',
    companyIntegrationId: 'afa9ad7a-8dbc-4837-9acb-9f0ef6140a63',
  },
  {
    isArchived: false,
    isCreatedByClient: false,
    isEnableGroupBy: false,
    isLive: false,
    isMarkedDeleted: false,
    limit: 100,
    clickActions: {
      card: {
        isEnable: false,
        baseUrl: '',
        dynamic: 'none',
        route: '',
        routeType: 'internal',
      },
      chart: {
        isEnable: false,
        baseUrl: '',
        dynamic: '{{value}}',
        route: '/{{value}}',
        routeType: 'internal',
      },
    },
    joinFields: [],
    chartOptions: {
      step: '',
      xAxis: '__timestamp',
      margins: {
        marginTop: 20,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 20,
      },
      measure: '',
      chartType: 'time series',
      yAxisList: ['sum(sales)'],
      seriesField: 'product_line',
      singleValue: '',
      axisSettings: {
        axis: 'left',
      },
      sankeyValues: [],
      labelSettings: {
        axis: 'left',
        show: false,
        position: 'hidden',
        truncateLabelValue: 14,
      },
      tableSettings: {
        lineGap: 'small',
        enableFilter: true,
        showRowHover: false,
        enableSorting: true,
        showTableDesc: false,
        defaultRowSize: '10',
        showTableTitle: false,
        contentAlignment: 'center',
        enableStripedRows: false,
        enableTableSearch: true,
        hideVerticalDivider: false,
      },
      customSettings: {
        barWidth: 40,
        fontSize: 14,
        barRadius: 0,
        xRotation: 50,
        axisLabels: 'none',
        displayText: '',
        dateFormatter: 'none',
        hideAxisLines: 'none',
        subHeaderShow: false,
        hideSplitLines: 'none',
        numberFormatter: 'original',
        showLabelValues: false,
        subHeaderFontSize: 0,
      },
      legendSettings: {
        top: 0,
        left: 0,
        show: true,
        right: 0,
        bottom: 0,
        position: 'horizontal',
        truncateLegendValue: 14,
      },
      backGroundColor: {
        show: false,
      },
      isMultiDimension: true,
      timeSeriesSettings: {
        seriesType: [
          {
            type: 'stack',
            column: 'sum(sales)',
          },
        ],
        groupBySettings: {
          value: 'monthly',
          options: [],
          isDynamic: false,
        },
      },
    },
    datasetMetricSettings: '',
    drillDownSettings: {
      isEnableGroupBy: false,
    },
    groupBy: {},
    inputFields: [],
    resizeAttributes: {
      width: 5,
      xAxis: 0,
      yAxis: 0,
      height: 10,
    },
    rlsConditions: [],
    selectedGroupBy: [],
    clientId: null,
    createdBy: 'Sapna Singh',
    description: '',
    integrationName: 'Redshift',
    metricId: 'demo_quaterly_sales',
    metricQuery: '',
    name: 'Quarterly Sales (By Product Line)',
    outputColumns: '',
    query:
      'SELECT DATE_TRUNC(\'quarter\', order_date) AS __timestamp,\r\n       product_line AS product_line,\r\n       sum(sales) AS "SUM(Sales)"\r\nFROM public.cleaned_sales_data\r\nGROUP BY product_line,\r\n         DATE_TRUNC(\'quarter\', order_date)\r\nORDER BY "SUM(Sales)" DESC limit 100',
    timeGrain: null,
    companyId: '5c00f9ce-9153-42cf-a25a-17b422ec38b2',
    companyIntegrationId: 'afa9ad7a-8dbc-4837-9acb-9f0ef6140a63',
  },
  {
    isArchived: false,
    isCreatedByClient: false,
    isEnableGroupBy: false,
    isLive: false,
    isMarkedDeleted: false,
    limit: 100,
    clickActions: {
      card: {
        isEnable: false,
        baseUrl: '',
        dynamic: 'none',
        route: '',
        routeType: 'internal',
      },
      chart: {
        isEnable: false,
        baseUrl: '',
        dynamic: '{{value}}',
        route: '/{{value}}',
        routeType: 'internal',
      },
    },
    joinFields: [],
    chartOptions: {
      step: '',
      xAxis: 'product_line',
      margins: {
        marginTop: 20,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 20,
      },
      measure: '',
      chartType: 'doughnut',
      yAxisList: ['(sales)'],
      singleValue: '',
      axisSettings: {
        axis: 'left',
      },
      sankeyValues: [],
      labelSettings: {
        show: true,
        step: '',
        xAxis: 'product_line',
        margins: {
          marginTop: 20,
          marginLeft: 5,
          marginRight: 5,
          marginBottom: 20,
        },
        measure: '',
        position: 'top',
        chartType: 'doughnut',
        yAxisList: ['(sales)'],
        singleValue: '',
        axisSettings: {
          axis: 'left',
        },
        sankeyValues: [],
        labelSettings: {
          axis: 'left',
          show: false,
          position: 'hidden',
          truncateLabelValue: 14,
        },
        tableSettings: {
          lineGap: 'small',
          enableFilter: true,
          showRowHover: false,
          enableSorting: true,
          showTableDesc: false,
          defaultRowSize: '10',
          showTableTitle: false,
          contentAlignment: 'center',
          enableStripedRows: false,
          enableTableSearch: true,
          hideVerticalDivider: false,
        },
        customSettings: {
          barWidth: 40,
          fontSize: 14,
          barRadius: 0,
          xRotation: 50,
          axisLabels: 'none',
          displayText: '',
          dateFormatter: 'none',
          hideAxisLines: 'none',
          subHeaderShow: false,
          hideSplitLines: 'none',
          numberFormatter: 'original',
          showLabelValues: false,
          subHeaderFontSize: 0,
        },
        legendSettings: {
          top: 0,
          left: 0,
          show: true,
          right: 0,
          bottom: 0,
          position: 'horizontal',
          truncateLegendValue: 14,
        },
        backGroundColor: {
          show: false,
        },
        timeSeriesSettings: {
          seriesType: [
            {
              type: 'bar',
              column: '(sales)',
            },
          ],
          groupBySettings: {
            value: 'monthly',
            options: [],
            isDynamic: false,
          },
        },
      },
      tableSettings: {
        lineGap: 'small',
        enableFilter: true,
        showRowHover: false,
        enableSorting: true,
        showTableDesc: false,
        defaultRowSize: '10',
        showTableTitle: false,
        contentAlignment: 'center',
        enableStripedRows: false,
        enableTableSearch: true,
        hideVerticalDivider: false,
      },
      customSettings: {
        barWidth: 40,
        fontSize: 14,
        barRadius: 0,
        xRotation: 50,
        axisLabels: 'none',
        displayText: '',
        dateFormatter: 'none',
        hideAxisLines: 'none',
        subHeaderShow: false,
        hideSplitLines: 'none',
        numberFormatter: 'original',
        showLabelValues: false,
        subHeaderFontSize: 0,
      },
      legendSettings: {
        top: 0,
        left: 0,
        show: true,
        right: 0,
        bottom: 0,
        position: 'horizontal',
        truncateLegendValue: 14,
      },
      backGroundColor: {
        show: false,
      },
      timeSeriesSettings: {
        seriesType: [
          {
            type: 'bar',
            column: '(sales)',
          },
        ],
        groupBySettings: {
          value: 'monthly',
          options: [],
          isDynamic: false,
        },
      },
    },
    datasetMetricSettings: '',
    drillDownSettings: null,
    groupBy: false,
    inputFields: '',
    resizeAttributes: {
      width: 5,
      xAxis: 0,
      yAxis: 0,
      height: 10,
    },
    rlsConditions: [],
    selectedGroupBy: [],
    clientId: null,
    createdBy: 'Sapna Singh',
    description: '',
    integrationName: 'Redshift',
    metricId: 'demo_total_revenue_product_line',
    metricQuery: '',
    name: 'Total Revenue (By Product Line)',
    outputColumns: '',
    query:
      'SELECT product_line AS product_line,\r\n       sum(sales) AS "(Sales)"\r\nFROM public.cleaned_sales_data\r\nGROUP BY product_line\r\nORDER BY "(Sales)" DESC limit 100',
    timeGrain: null,
    companyId: '5c00f9ce-9153-42cf-a25a-17b422ec38b2',
    companyIntegrationId: 'afa9ad7a-8dbc-4837-9acb-9f0ef6140a63',
  },
];
export const layout = [
  {
    h: 8,
    i: 'c397ef57-e91b-4844-a1a3-064ccd5d002a',
    w: 3,
    x: 0,
    y: 0,
    maxH: 15,
    minH: 5,
    minW: 3,
    moved: false,
    static: false,
  },
  {
    h: 8,
    i: '711227fa-69f3-4a64-a4ee-41f869d0dd21',
    w: 9,
    x: 3,
    y: 0,
    maxH: 15,
    minH: 8,
    minW: 3,
    moved: false,
    static: false,
  },
  {
    h: 10,
    i: 'e478dc7c-72f2-4e22-a4bb-ee9af229c87a',
    w: 12,
    x: 0,
    y: 18,
    maxH: null,
    minH: 8,
    minW: 3,
    moved: false,
    static: false,
  },
  {
    h: 10,
    i: 'd887a8a9-3f0b-4a6d-b131-801ee96a6c3c',
    w: 7,
    x: 5,
    y: 8,
    maxH: 15,
    minH: 8,
    minW: 3,
    moved: false,
    static: false,
  },
  {
    h: 10,
    i: 'aaf06f68-0ff9-4718-ae31-2c0b42b04184',
    w: 5,
    x: 0,
    y: 8,
    maxH: 15,
    minH: 8,
    minW: 3,
    moved: false,
    static: false,
  },
];
