const defaultTheme = require('tailwindcss/defaultTheme');
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  important: true,
  prefix: 'dbn-',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--dbn-typography-fontFamily)', 'Inter'],
        lato: ['var(--dbn-typography-fontFamily-lato)', 'sans-serif'],
      },
      fontWeight: {
        thin: 'var(--dbn-typography-fontWeightThin)',
        light: 'var(--dbn-typography-fontWeightLight)',
        normal: 'var(--dbn-typography-fontWeightRegular)',
        semibold: 'var(--dbn-typography-fontWeightSemibold)',
        bold: 'var(--dbn-typography-fontWeightBold)',
        extrabold: 'var(--dbn-typography-fontWeightExtraBold)',
      },
      screens: {
        xs: 'var(--dbn-breakpoint-xs)',
        ...defaultTheme.screens,
      },
      borderRadius: {
        none: 'var(--dbn-border-radiusNone)',
        sm: 'var(--dbn-border-radiusSm)',
        DEFAULT: 'var(--dbn-border-radiusDefault)',
        md: 'var(--dbn-border-radiusMd)',
        lg: 'var(--dbn-border-radiusLg)',
        xl: 'var(--dbn-border-radiusXl)',
        '2xl': 'var(--dbn-border-radius2xl)',
        '3xl': 'var(--dbn-border-radius3xl)',
        full: 'var(--dbn-border-radiusFull)',
      },
      zIndex: {
        background: 'var(--dbn-zIndex-background)',
        base: 'var(--dbn-zIndex-base)',
        foreground: 'var(--dbn-zIndex-foreground)',
        elevated: 'var(--dbn-zIndex-elevated)',
        portal: 'var(--dbn-zIndex-portal)',
        overlay: 'var(--dbn-zIndex-overlay)',
      },

      colors: {
        primary: 'rgba(var(--dbn-color-primary), <alpha-value>)',
        'primary-dark': 'rgba(var(--dbn-color-primaryDark), <alpha-value>)',
        secondary: 'rgba(var(--dbn-color-secondary), <alpha-value>)',
        'secondary-dark': 'rgba(var(--dbn-color-secondaryDark), <alpha-value>)',
        'alert-light': 'rgba(var(--dbn-color-alertLight), <alpha-value>)',
        alert: 'rgba(var(--dbn-color-alert), <alpha-value>)',
        'alert-dark': 'rgba(var(--dbn-color-alertDark), <alpha-value>)',
        info: 'rgba(var(--dbn-color-info), <alpha-value>)',
        'info-light': 'rgba(var(--dbn-color-infoLight), <alpha-value>)',
        white: 'rgba(var(--dbn-color-white), <alpha-value>)',
        gray: 'rgba(var(--dbn-color-gray), <alpha-value>)',
        'gray-dark': 'rgba(var(--dbn-color-grayDark), <alpha-value>)',
        success: 'rgba(var(--dbn-color-success), <alpha-value>)',
        'success-dark': 'rgba(var(--dbn-color-successDark), <alpha-value>)',
        'success-light': 'rgba(var(--dbn-color-successLight), <alpha-value>)',
        warning: 'rgba(var(--dbn-color-warning), <alpha-value>)',
        'warning-dark': 'rgba(var(--dbn-color-warningDark), <alpha-value>)',
        focus: 'var(--dbn-color-focus)',
        infoAlert: 'var(--dbn-color-infoAlert)',
        infoAlertLight: 'var(--dbn-color-infoAlertLight)',

        'client-text': 'var(--dbn-color-h5)',
        'text-placeholder': 'var(--dbn-color-h6)',
        subValue: 'var(--dbn-color-h7)',
        'gray-3': 'var(--dbn-color-h8)',
        'no-text': 'var(--dbn-color-red)',
        'success-text': 'var(--dbn-color-successText)',
        search: 'var(--dbn-color-graySearch)',
        background: 'var(--dbn-color-background)',
        'dark-silver': 'var(--dbn-color-darkSilver)',
        'primary-light': 'var(--dbn-color-primaryLight)',
        'secondary-light': 'var(--dbn-color-secondaryLight)',
        tertiary: 'var(--dbn-color-tertiary)',
        'tertiary-dark': 'var(--dbn-color-tertiaryDark)',
        'tertiary-light': 'var(--dbn-color-tertiaryLight)',
        dark: 'var(--dbn-color-dark)',
        light: 'var(--dbn-color-light)',
        'warning-light': 'var(--dbn-color-warningLight)',
        error: 'var(--dbn-color-error)',
        'error-medium': 'var(--dbn-color-errorMedium)',
        'error-dark': 'var(--dbn-color-errorDark)',
        'error-light': 'var(--dbn-color-errorLight)',
        disabled: 'var(--dbn-color-disabled)',
        'bright-gray': 'var(--dbn-color-brightGray)',
        'gray-50': 'var(--dbn-color-gray50)',
        'gray-100': 'var(--dbn-color-gray100)',
        'gray-200': 'var(--dbn-color-gray200)',
        'gray-300': 'var(--dbn-color-gray300)',
        'gray-400': 'var(--dbn-color-gray400)',
        'gray-500': 'var(--dbn-color-gray500)',
        'gray-600': 'var(--dbn-color-gray600)',
        'gray-700': 'var(--dbn-color-gray700)',
        'gray-800': 'var(--dbn-color-gray800)',
        'gray-900': 'var(--dbn-color-gray900)',
        'text-primary-color': 'var(--dbn-typography-colorPrimary)',
        'text-secondary-color': 'var(--dbn-typography-colorSecondary)',
        'text-tertiary-color': 'var(--dbn-typography-colorTertiary)',
        'background-light': 'var(--dbn-color-backgroundLight)',
        'text-light': 'var(--dbn-typography-colorLight)',
        blue: {
          h1: '#EAEEFC',
          h2: 'rgb(88, 101, 246, 0.1)',
          h3: 'rgba(88, 101, 246, 0.2)',
          h4: '#5865F6',
          h5: '#51649C',
          h6: 'rgba(255, 255, 255, 0.2)',
          h7: '#182C60',
          h8: '#F4F6FF',
          h9: 'rgba(88, 101, 246, 0.16)',
          h10: '#30447C',
          h11: '#DDE2F0',
          h12: '#95A1C2',
          h13: '#223771',
          h14: '#D7E0FA',
          h15: '#C0CCF5',
          h16: '#080B54',
          h17: '#7384B6',
          h18: '#BABDFF',
          h19: '#F9FBFE',
          h20: '#FAF6FC',
          h21: '#2D2CAD',
          h22: '#F4F6FC',
          h23: 'rgba(79, 122, 255, 0.2)',
          h24: 'rgba(59, 205, 249, 0.2)',
        },
        green: {
          h1: 'rgba(12, 190, 105, 0.1)',
          h2: '#0CBE69',
          h3: '#CBF4C9',
          h5: 'rgba(22, 212, 111, 0.2)',
        },
        red: {
          h1: '#FF3030',
          h2: '#F56700',
          h3: 'rgba(252, 105, 42, 0.2)',
          h4: '#ff0000',
          h5: '#ff1111',
        },
        disabled: '#CCCCCC',
        'error-medium': '#FF100F',
        'gray-light': 'rgba(13, 13, 13, 0.60)',
      },
      fontSize: {
        xxs: 'var(--dbn-typography-fontSize)', //9px
      },
      letterSpacing: {
        'ls-1': '0.013rem', //0.2px
      },
      boxShadow: {
        primary: 'var(--dbn-shadow-primary)',
        secondary: 'var(--dbn-shadow-secondary)',
        tertiary: 'var(--dbn-shadow-tertiary)',
        'bs-1': '0px 2px 8px rgba(88, 101, 246, 0.16)',
        'bs-2': '-4px 4px 10px rgba(88, 101, 246, 0.12)',
        'bs-3': '0px 4px 14px rgba(88, 101, 246, 0.15)',
        'bs-4': '0 2px 10px 0 rgba(0,0,0,0.3)',
        'bs-5': '0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
        'bs-6': 'var(--dbn-shadow-dropDown)',
        'bs-7': '0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
        'bs-8':
          '0px 1px 2px 0px rgba(0, 0, 0, 0.06), 0px 1px 3px 0px rgba(0, 0, 0, 0.10)',
        'bs-9': '0px 4px 16px 0px rgba(0, 0, 0, 0.08)',
        'bs-10': '0px 8px 20px 0px rgba(0, 0, 0, 0.05)',
        'bs-11': '0px 4px 4px 0px rgba(0, 0, 0, 0.05)',
        'bs-12': 'var(--dbn-shadow-input)',
        'bs-13': '0px 8px 20px 0px rgba(0, 0, 0, 0.10)',
      },
    },
  },
  plugins: [],
};
